### ISSUE TITLE
Reload policy configuration

### ISSUE THREAD

**Issue by fileman** [PolicyServer/PolicyServer.Local#4]
Hi, this version can reload configuration file?
I've tried with reloadonchange in AddJson file no reload of modified data.
I don't see method for configuration outside ConfigureServices in startup.cs

thanks

**Comment by leastprivilege** [comment]
We didn't specifically code for that - but by using the standard config APIs this should work. 

I can look into it - or you and PR. thanks!

**Comment by TsengSR** [comment]
@fileman: In order for the options to be reloaded on file change, `IOptionsSnapshot<T>` needs to be injected instead of `IOptions<T>` (see [docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options#reload-configuration-data-with-ioptionssnapshot)). Nothing else changes. 

That's all, shouldn't be too hard to fix and do an PR. Just on work right now.

**Comment by fileman** [comment]
IOptionSnapshot<T> is my first change:
`services.AddSingleton(r => r.GetRequiredService<IOptionsSnapshot<Policy>>().Value);`
but return this exception:
`InvalidOperationException: Cannot resolve scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot'1[PolicyServer.Local.Policy]' from root provider`

**Comment by TsengSR** [comment]
@fileman: It must not be singleton. Just register the options as scoped and it will work. Dunno why someone registered it as scoped anyways. Options are supposed to be scoped anyways.

The background is, that you don't want options to be changed in mid of a request when a the file changes. `IOptionsSnapshot<T>` will apply the changed options on the next request

**Comment by fileman** [comment]
I've tried to change AddSingleton into AddScoped but doesn't work. see this #5 comment

**Comment by TsengSR** [comment]
Mhh the essence of the problem is that (most likely) `ActionDescriptorCollectionProvider` (which implements `IActionDescriptorCollectionProvider`) is registered as singleton and for some reason it resolves the `AuthorizationHandler<T>`'s  (who inject `IPolicyServerClient`) during startup before there's a request (hence no httpcontext and no scoped services). So it fails to resolve the handlers.

I'm not sure yet where and why it happens, but an alternative may be to Inject `IHttpContextAccessor` instead of `IPolicyServerClient` and then resolve `IPolicyServerClient` from the `HttpContext` inside `HandleRequirementAsync`, assuming the `IActionDescriptorCollectionProvider` doesn't call `HandleRequirementAsync` (didn't tried, its late).

**Comment by fileman** [comment]
@TsengSR your suggestion is ok, I can add new commit so @brockallen can review it, but I've a doubt,
is better:
`services.AddScoped(r => r.GetRequiredService<IOptionsSnapshot<Policy>>().Value);
services.AddTransient<IPolicyServerClient, PolicyServerClient>();`
or
`services.AddScoped(r => r.GetRequiredService<IOptionsSnapshot<Policy>>().Value);
services.AddScoped<IPolicyServerClient, PolicyServerClient>();`

**Comment by brockallen** [comment]
fixed/done
